[[questions]]

question = "What was Meta Platforms Inc formerly known as"
answer = "Facebook"
alternatives = ["Google", "Apple", "Dell"]

[[questions]]

question = "Which English city is known as the Steel City"
answer = "Sheffield"
alternatives = ["London", "Manchester", "Liverpool"]

[[questions]]

question = "Which former British colony was given back to China in 1997"
answer = "Hong Kong"
alternatives = ["Shanghai", "Beijing", "Wuhan"]

[[questions]]

question = "The logo for luxury car maker Porsche features which animal"
answer = "Horse"
alternatives = ["Goat", "Eagle", "Snake"]

[[questions]]

question = "Which element is said to keep bones strong"
answer = "Calcium"
alternatives = ["Chromium", "Titanium", "Helium"]

