[general]
label = "General questions"

[[general.questions]]

question = "What was Meta Platforms Inc formerly known as"
answers = ["Facebook"]
alternatives = ["Google", "Apple", "Dell"]
explanation = """
    Meta Platforms, Inc., doing business as Meta and formerly named Facebook, Inc.,
    and TheFacebook, Inc., is an American multinational technology conglomerate based in Menlo Park,
    California. The company owns Facebook, Instagram, and WhatsApp, among other products and services.
    Meta is one of the world's most valuable companies. It is considered one of the Big Five American
    information technology companies, alongside Alphabet, Amazon, Apple, and Microsoft.
"""

[[general.questions]]

question = "Which English city is known as the Steel City"
answers = ["Sheffield"]
alternatives = ["London", "Manchester", "Liverpool"]

[[general.questions]]

question = "Which former British colony was given back to China in 1997"
answers = ["Hong Kong"]
alternatives = ["Shanghai", "Beijing", "Wuhan"]

[[general.questions]]

question = "The logo for luxury car maker Porsche features which animal"
answers = ["Horse"]
alternatives = ["Goat", "Eagle", "Snake"]

[[general.questions]]

question = "Which element is said to keep bones strong"
answer = ["Calcium"]
alternatives = ["Chromium", "Titanium", "Helium"]
explanation = """
    Calcium is a common constituent of multivitamin dietary supplements,but the composition of
    calcium complexes in supplements may affect its bioavailability which varies by solubility
    of the salt involved: calcium citrate, malate, and lactate are highly bioavailable, while
    the oxalate is less.
"""

[[general.questions]]

question = "What elements water consists of"
answers = ["Helium", "Oxygen"]
alternatives = ["Chromium", "Titanium", "Calcium"]
hint = "Water formula is H20"

[movies]
label = "Movies"

[[movies.questions]]
question = "Who directed 'Pulp Fiction'"
answers = ["Quentin Tarantino"]
alternatives = ["Stiven Spielbeg", "Martin Scorsese", "Christopher Nolan"]
hint = "This director also shot 'Reservoir Dogs' and 'Kill Bill'"

[[movies.questions]]
question = "What is the Russian boxer Rocky fights in Rocky IV called"
answers = ["Ivan Drago"]
alternatives = ["Boris Ivanov", "Sergei Petukhov", "Foma Kiniaev"]
hint = "Dolph Lundgren played him"